CHUNK_SIZE = 100

DIR_UP = f"../"
OUTPUT_DIR = f"{DIR_UP}resources/"

OUTPUT_FILENAME = f"output_array.pkl"
OUTPUT_FILEPATH = f"{OUTPUT_DIR}{OUTPUT_FILENAME}"
OUTPUT_CHUNK = (1, 61190)
OUTPUT_SHAPE = (12000, 61190)

CLASS_LABELS_FILENAME = f"newsgrouplabels.txt"
CLASS_LABELS_FILEPATH = f"cs429529-project-2-topic-categorization/{CLASS_LABELS_FILENAME}"
