# TODO: save weights matrix to file (load weights matrix from file on start)
# TODO: save log of the prediction vector and other stats (every time program is run, every n iterations,...)
# TODO: maybe run on Wheeler...
# TODO: compute W matrix afterwards (just numpy array) -- AFTER cluster/client closes...
# TODO: maybe experiment so computation is completed after a few iterations...

# TODO: fix parent directory
